[package]
name = "proc-macro-grouping-hygiene-bug"
version = "0.1.0"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Mara Bos <m-ou.se@m-ou.se>",
]

edition = "2018"

[lib]
proc-macro = true
